# Generated by Django 2.2 on 2020-04-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teaching_subjects',
            field=models.ManyToManyField(to='smsapp.Subject', verbose_name='Teaching Subjects'),
        ),
        migrations.AlterField(
            model_name='classsetup',
            name='class_teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='smsapp.Teacher', verbose_name='Teacher'),
        ),
    ]
